# Site settings
title: Jekyll Seed
safe:           false
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - bundle/
  - README.md
timezone: America/New_York
highlighter: false 

baseurl: ""
