# Site settings
title: Jekyll Seed
safe: false
source: app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false 

collections:
  about:
    output: true
  partners:
    output: true
  developers:
    output: true
  methodology:
    output: true
  usecases:
    output: true
  resources:
    output: true
  datasets:
    output: true