# Site settings
title: Iran Open Data
safe: false
source: app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false 

collections:
  about:
    output: true
  partners:
    output: true
  developers:
    output: true
  methodology:
    output: true
  usecases:
    output: true
  resources:
    output: true
  en_datasets:
    output: true
    permalink: /en/datasets/:path/
  fa_datasets:
    output: true
    permalink: /fa/datasets/:path/
  involve:
    output: true
